[audio]
enable = true # wip
stereo = true # wip

[audio.vol]
fx = 0.05
ost = 0.05
master = 1.0

[debug]

[debug.console]
enable = true     # wip
theme = "default" # wip

[debug.log]
enable = true     # wip
style = "default" # wip

[debug.skip]
enable = true
target = "shell"                # allowed values: shell | main_menu
skip_gamestage_animation = true
parameters = ["silo"]           # wip

[graphics]
theme = "default"             # wip
entities_show_on_menu = false # not fully implemented / wip
splashtexts_show = true
fullscreen = false            # wip
res_w = 1                     # wip
res_h = 1                     # wip

[graphics.crt]
enable = true

[cli]
catch_errors = false
global_flags = ["v"]
global_flags_on_startup_arguments = [] # wip, if empty uses global flags
ignore_buildinfo = false
