global using AsitLib;
global using AsitLib.Diagnostics;
global using AsitLib.Numerics;
global using AsitLib.Chance;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Content;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using Microsoft.Xna.Framework.Media;
global using MonoGame.Extended;
global using MonoGame.Extended.Graphics;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Autofac;
global using ButtonState = Microsoft.Xna.Framework.Input.ButtonState;
global using Color = Microsoft.Xna.Framework.Color;
global using Point = Microsoft.Xna.Framework.Point;
global using Rectangle = Microsoft.Xna.Framework.Rectangle;
global using Environment = STOLON.Environment;
//global using IDrawable = STOLON.IDrawable;
global using Math = System.Math;
global using Vector2 = Microsoft.Xna.Framework.Vector2;
global using RectangleF = MonoGame.Extended.RectangleF;