<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RollForward>Major</RollForward>
		<PublishReadyToRun>false</PublishReadyToRun>
		<TieredCompilation>false</TieredCompilation>
		<BaseOutputPath>..\..\build</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="AsitLib">
			<HintPath>./lib/AsitLib.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Icon.ico" />
		<EmbeddedResource Include="Icon.bmp" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Betwixt" Version="1.4.1">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="DiscordRichPresence" Version="1.2.1.24" />
		<PackageReference Include="MonoGame.Extended" Version="4.1.0" />
		<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.3" />
		<PackageReference Include="NAudio" Version="2.2.1" />
		<PackageReference Include="Tomlyn" Version="0.19.0" />
	</ItemGroup>

	<ItemGroup>
		<SLBuildAssets Include="static-assets\**\*.*" />
	</ItemGroup>
	<Target Name="DepositAssets" AfterTargets="Build">
		<Copy SourceFiles="@(SLBuildAssets)" DestinationFiles="@(SLBuildAssets->'$(OutputPath)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="True"/>
	</Target>
</Project>