<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<BaseOutputPath>..\..\build</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="AsitLib">
			<HintPath>..\STOLON\lib\AsitLib.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Include="..\STOLON\resources\**\*.*" Link="resources\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\STOLON\STOLON.csproj" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DebugBuildCondition>True</DebugBuildCondition>
	</PropertyGroup>
	<Target Name="CreateBuildInfoFolder" AfterTargets="AfterBuild">
		<Exec Command="powershell.exe -ExecutionPolicy Bypass -File $(ProjectDir)..\..\scripts\build.ps1 -BuildConfiguration $(Configuration) -ProjPath $(ProjectDir) -DebugBuild $(DebugBuildCondition)" WorkingDirectory="$(MSBuildThisFileDirectory)..\..\scripts" />
	</Target>
</Project>
