<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<BaseOutputPath>..\..\build</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="AsitLib">
			<HintPath>..\STOLON\PostBuild\AsitLib.dll</HintPath>
		</Reference>
		<SLBuildAssets Include="..\STOLON\PostBuild\**\*.*" Exclude="..\STOLON\PostBuild\**\.gitkeep" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\STOLON\PostBuild\**\*.*" Link="PostBuild\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\STOLON\STOLON.csproj" />
	</ItemGroup>
	<Target Name="DepositAssets" AfterTargets="Build">
		<Copy SourceFiles="@(SLBuildAssets)" DestinationFiles="@(SLBuildAssets->'$(OutputPath)%(RecursiveDir)%(Filename)%(Extension)')" />
	</Target>

	<PropertyGroup>
		<DebugBuildCondition Condition="'$(Configuration)' == 'Debug'">true</DebugBuildCondition>
	</PropertyGroup>
	<Target Name="CreateBuildInfoFolder" AfterTargets="Build" Condition="'$(DebugBuildCondition)' == 'true'">
		<Exec Command="powershell.exe -ExecutionPolicy Bypass -File $(ProjectDir)..\..\scripts\build_debug.ps1 -BuildPath $(OutDir) -ProjPath $(ProjectDir)" />
	</Target>
</Project>
