<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RollForward>Major</RollForward>
		<PublishReadyToRun>false</PublishReadyToRun>
		<TieredCompilation>false</TieredCompilation>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Content\bin\**" />
		<Compile Remove="Content\obj\**" />
		<EmbeddedResource Remove="Content\bin\**" />
		<EmbeddedResource Remove="Content\obj\**" />
		<EmbeddedResource Remove="Content\Textures\Entities\**" />
		<None Remove="Content\bin\**" />
		<None Remove="Content\obj\**" />
		<None Remove="Content\Textures\Entities\**" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="AsitLib">
			<HintPath>./../libs/AsitLib.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Remove="Icon.ico" />
		<None Remove="Icon.bmp" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Icon.ico" />
		<EmbeddedResource Include="Icon.bmp" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Betwixt" Version="1.4.1">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="DiscordRichPresence" Version="1.2.1.24" />
		<PackageReference Include="MonoGame.Extended" Version="4.1.0" />
		<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.3" />
		<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
		<PackageReference Include="NAudio" Version="2.2.1" />
		<PackageReference Include="Nopipeline.Task" Version="2.3.0" />
		<PackageReference Include="Salaros.ConfigParser" Version="0.3.8" />
	</ItemGroup>
	<ItemGroup>
		<NPLContentReferences Remove="..\Content\bin\**" />
	</ItemGroup>
	<ItemGroup>
		<MGCBContentReferences Remove="..\Content\bin\**" />
	</ItemGroup>
	<ItemGroup>
		<NPLContentReferences Remove="..\Content\obj\**" />
	</ItemGroup>
	<ItemGroup>
		<MGCBContentReferences Remove="..\Content\obj\**" />
	</ItemGroup>
</Project>